# add the linters you want stickler to use for this project
linters:
  eslint:
    config: './client/.eslintrc.json'

  rubocop:
    display_cop_names: true
    config: './rubocop.yml'

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"