export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_EVENTS_FOLLOWED = 'LOAD_EVENTS_FOLLOWED';

export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';

export const ADD_EVENT_FOLLOWER = 'ADD_EVENT_FOLLOWER';
export const LOAD_EVENT_FOLLOWERS = 'LOAD_EVENT_FOLLOWERS';
export const DELETE_EVENT_FOLLOWER = 'DELETE_EVENT_FOLLOWER';

export const RESET = 'RESET';
