export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_EVENTS_FOLLOWERS = 'LOAD_EVENTS_FOLLOWERS';
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';
